jdbc.driver=com.mysql.jdbc.Driver
jdbc.url=jdbc:mysql:///seckill?useUnicode=true&characterEncoding=utf8&useSSL=false
jdbc.username=root
jdbc.password=acedata1706

#qiniu
qiniu.ak=XeDrNJmVc8_bQUW3GgpDs8vxSj1luHekgIDsktGx
qiniu.sk=b4h4sdQFimYPUACmLmcPhviVgaoCQZH6ugud0--o
qiniu.buket=retail

#redis
redis.host=192.168.0.120
redis.port=6379
redis.auth=acedata1706
redis.max.active=1024
redis.max.idle=200
redis.max.wait=10000
redis.time.out=10000
redis.on.borrow=true
redis.database=0
redis.timeout=2000