server:
  port: 8081

#  RMQ
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    # 消费者数量
    listener:
      simple:
        concurrency: 10
        max-concurrency: 10
        # 每次从队列中取的消息个数，prefetch来限制Queue每次发送给每个消费者的消息数，设置为1表明，queue每次会发送1个消息给consumer，等到收到consumer的ack后，queue才会继续发消息给consumer
        prefetch: 1
        # 消费者默认启动
        auto-startup: true
        acknowledge-mode: manual
        # 允许消费者消费失败后，将消息重新压入队列中
        default-requeue-rejected: true
      direct:
        acknowledge-mode: manual
    template:
      # 失败重试
      retry:
        enabled: false
    #如果没有本条配置信息，当消费者收到生产者发送的消息后，生产者无法收到确认成功的回调信息
    publisher-confirm-type: correlated
