version: '2'
services:
  # Graylog: https://hub.docker.com/r/graylog/graylog/
  graylog:
    image: graylog/graylog-enterprise:4.1
    environment:
      # 密码加密盐值，不能小于16个字符
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # 用户名配置项，默认为admin
      - GRAYLOG_ROOT_USERNAME=admin
      # 此处的密码是经过SHA2算法加密后的密码，默认为admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      # 这里需要填一个可以在外部访问的地址，我这里填的是宿主机的地址，否则无法通过浏览器访问
      - GRAYLOG_HTTP_EXTERNAL_URI=http://122.112.234.109:9000/
      # 配置Elasticsearch连接地址，多节点使用逗号分隔
      - GRAYLOG_ELASTICSEARCH_HOSTS=http://192.168.1.3:9020
      # 配置MongoDB连接地址，多节点使用逗号分隔
      - GRAYLOG_MONGODB_URI=mongodb://192.168.1.3:9017/graylog
      # 配置时区
      - GRAYLOG_ROOT_TIMEZONE=Asia/Shanghai
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
