server:
  port: 8089

spring:
  application:
    name: seckill-es
  #关闭 thymeleaf 缓存
  thymeleaf:
    cache: false
  elasticsearch:
    rest:
      uris: http://122.112.234.109:9020


feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
