jdbc.driver=com.mysql.jdbc.Driver
jdbc.url=jdbc:mysql:///seckill?useSSL=false
jdbc.username=root
jdbc.password=rootroot

#qiniu
qiniu.ak=XeDrNJmVc8_bQUW3GgpDs8vxSj1luHekgIDsktGx
qiniu.sk=b4h4sdQFimYPUACmLmcPhviVgaoCQZH6ugud0--o
qiniu.buket=retail

#redis
redis.host=127.0.0.1
redis.port=6379
redis.auth=redis
redis.max.active=1024
redis.max.idle=200
redis.max.wait=10000
redis.time.out=10000
redis.on.borrow=true