server:
  port: 8082

spring:
  application:
    name: seckill-goods
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    lettuce:
      pool:
        max-idle: 10
        min-idle: 2
        max-active: 20
        max-wait: 2000
    password:



feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
