server:
  port: 8087

spring:
  application:
    name: seckill-mongo
  data:
    mongodb:
      uri: mongodb://122.112.234.109:9017/movie

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core: DEBUG
